#!/usr/bin/env ruby

puts "Starting..."

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

def create_entry(status, tweet)
  Entry.create( :guid => status.id, 
                :description => status.text, 
                :pub_time => status.created_at.to_s(:db),
                :link => "https://twitter.com/#!/#{status.screen_name}/status/#{status.id}",
                :image => status.user.profile_image_url,
                :source => tweet)
end

Tweet.all.each do |tweet|
  if tweet.username.present?
    raw_statuses = Twitter.user_timeline(tweet.username)
    statuses = raw_statuses.collect do |s|
      { :id => s.id,
        :text => s.text,
        :created_at => s.created_at,
        :screen_name => s.user.screen_name,
        :image => s.user.profile_image_url_https }
    end
  elsif tweet.search_term.present?
    raw_statuses = Twitter.search(tweet.search_term, :result_type => 'recent')
    statuses = raw_statuses.collect do |s|
      { :id => s.id,
        :text => s.text,
        :created_at => s.created_at,
        :screen_name => s.from_user,
        :profile_image_url => s.profile_image_url_https }
    end
  end

  statuses.each do |status|
    if Entry.find_by_guid status.id
      puts "    Exiting, matched GUID"
      break
    else
      puts "  New entry: #{status.id}"
      create_entry(status, tweet)
    end
  end
  tweet.update_attribute :last_checked_at, Time.now
end

